insert into public.teams (name, short_name, logo_url) values
('Real Madrid', 'RMA', 'https://api.iconify.design/logos:real-madrid.svg'),
('FC Barcelona', 'FCB', 'https://api.iconify.design/logos:fc-barcelona.svg'),
('Atletico de Madrid', 'ATM', 'https://api.iconify.design/logos:atletico-madrid.svg'),
('Athletic Club', 'ATH', 'https://api.iconify.design/logos:athletic-club.svg'),
('Real Sociedad', 'RSO', 'https://api.iconify.design/logos:real-sociedad.svg'),
('Real Betis', 'BET', 'https://api.iconify.design/logos:real-betis.svg'),
('Sevilla FC', 'SEV', 'https://api.iconify.design/logos:sevilla.svg'),
('Villarreal CF', 'VIL', 'https://api.iconify.design/logos:villarreal.svg'),
('Valencia CF', 'VAL', 'https://api.iconify.design/logos:valencia-cf.svg'),
('Celta de Vigo', 'CEL', 'https://api.iconify.design/logos:celta-vigo.svg'),
('Getafe CF', 'GET', 'https://api.iconify.design/logos:getafe.svg'),
('Osasuna', 'OSA', 'https://api.iconify.design/logos:osasuna.svg'),
('Rayo Vallecano', 'RAY', 'https://api.iconify.design/logos:rayo-vallecano.svg'),
('RCD Mallorca', 'MAL', 'https://api.iconify.design/logos:mallorca.svg'),
('Girona FC', 'GIR', 'https://api.iconify.design/logos:girona.svg'),
('UD Las Palmas', 'LPA', 'https://api.iconify.design/logos:las-palmas.svg'),
('RCD Espanyol', 'ESP', 'https://api.iconify.design/logos:espanyol.svg'),
('Deportivo Alaves', 'ALA', 'https://api.iconify.design/logos:deportivo-alaves.svg'),
('Leganes', 'LEG', 'https://api.iconify.design/logos:cd-leganes.svg'),
('Real Valladolid', 'VLL', 'https://api.iconify.design/logos:real-valladolid.svg')
on conflict (name) do nothing;

insert into public.avatars (name, slug, image_url, active, sort_order) values
('Ivan Campo Ramos', 'ivan-campo', '/avatars/ivan-campo.png', true, 1),
('Thomas Gravesen', 'thomas-gravesen', '/avatars/thomas-gravesen.png', true, 2),
('Royston Drenthe', 'royston-drenthe', '/avatars/royston-drenthe.png', true, 3),
('Jonathan Woodgate', 'jonathan-woodgate', '/avatars/jonathan-woodgate.png', true, 4),
('Nordin Amrabat', 'nordin-amrabat', '/avatars/nordin-amrabat.png', true, 5),
('Julien Faubert', 'julien-faubert', '/avatars/julien-faubert.png', true, 6),
('Antonio Cassano', 'antonio-cassano', '/avatars/antonio-cassano.png', true, 7),
('Nicolas Anelka', 'nicolas-anelka', '/avatars/nicolas-anelka.png', true, 8),
('Dmytro Chygrynskyi', 'dmytro-chygrynskyi', '/avatars/dmytro-chygrynskyi.png', true, 9),
('Javier Saviola', 'javier-saviola', '/avatars/javier-saviola.png', true, 10),
('Robert Prosinecki', 'robert-prosinecki', '/avatars/robert-prosinecki.png', true, 11),
('Elvir Baljic', 'elvir-baljic', '/avatars/elvir-baljic.png', true, 12),
('Oleguer Presas Renom', 'oleguer-presas', '/avatars/oleguer-presas.png', true, 13),
('Cicero Joao de Cezare (Cicinho)', 'cicinho', '/avatars/cicinho.png', true, 14),
('Walter Samuel', 'walter-samuel', '/avatars/walter-samuel.png', true, 15),
('Pablo Garcia Fernandez', 'pablo-garcia', '/avatars/pablo-garcia.png', true, 16),
('Antonio Nunez Tena', 'antonio-nunez', '/avatars/antonio-nunez.png', true, 17),
('Engonga', 'engonga', '/avatars/engonga.png', true, 18),
('Ariza Makukula', 'ariza-makukula', '/avatars/ariza-makukula.png', true, 19),
('Aloisio', 'aloisio', '/avatars/aloisio.svg', true, 20),
('Oier', 'oier', '/avatars/oier.svg', true, 21),
('Portillo', 'portillo', '/avatars/portillo.svg', true, 22),
('Alpha One', 'placeholder-01', '/avatars/placeholder-01.svg', true, 23),
('Blaze Two', 'placeholder-02', '/avatars/placeholder-02.svg', true, 24),
('Cobra Three', 'placeholder-03', '/avatars/placeholder-03.svg', true, 25),
('Drift Four', 'placeholder-04', '/avatars/placeholder-04.svg', true, 26),
('Echo Five', 'placeholder-05', '/avatars/placeholder-05.svg', true, 27),
('Fury Six', 'placeholder-06', '/avatars/placeholder-06.svg', true, 28),
('Ghost Seven', 'placeholder-07', '/avatars/placeholder-07.svg', true, 29),
('Hawk Eight', 'placeholder-08', '/avatars/placeholder-08.svg', true, 30),
('Ion Nine', 'placeholder-09', '/avatars/placeholder-09.svg', true, 31),
('Jolt Ten', 'placeholder-10', '/avatars/placeholder-10.svg', true, 32),
('Knox Eleven', 'placeholder-11', '/avatars/placeholder-11.svg', true, 33),
('Lynx Twelve', 'placeholder-12', '/avatars/placeholder-12.svg', true, 34)
on conflict (slug) do nothing;

